#!/bin/bash

CP='cp -rT'

DIFF='diff -BbErwy --suppress-common-lines'

MKDIR='mkdir -p'

RM='rm -rf'

FILES='
conkyrc
i3
vimrc
xinitrc
Xmodmap
Xresources
zshrc
'

VIM_PATHOGEN='https://github.com/vim-scripts/pathogen.vim'
VIM_PLUGINS='
https://github.com/vim-scripts/php.vim-html-enhanced
https://github.com/vim-scripts/clang-complete
https://github.com/vim-scripts/ctrlp.vim
https://github.com/vim-scripts/fugitive.vim
https://github.com/vim-scripts/html5.vim
https://github.com/vim-scripts/javacomplete
https://github.com/vim-scripts/matchit.zip
https://github.com/vim-scripts/The-NERD-tree
https://github.com/Lokaltog/vim-powerline
https://github.com/vim-scripts/pythoncomplete
https://github.com/vim-scripts/QuickBuf
https://github.com/vim-scripts/snipMate
https://github.com/vim-scripts/taglist.vim
https://github.com/vim-scripts/tComment
'

function vim_install {
rm -rf ~/.vim 
mkdir -p ~/.vim/autoload
git clone $VIM_PATHOGEN
cp pathogen.vim/plugin/pathogen.vim ~/.vim/autoload
rm -rf pathogen.vim
mkdir -p ~/.vim/bundle
cd ~/.vim/bundle
for plugin in $VIM_PLUGINS
do
  git clone $plugin
done
cd ~/.vim/bundle
find -name ".git*" | xargs -l rm -rf
}

function show_help {
echo 'dotfiles {diff [file] | install [file] | vim-install | clean}'
}

case $1 in
  diff)
    if [ $2 ]
    then
      echo $DIFF $2 ~/.$2
      $DIFF $2 ~/.$2
    else
      for file in $FILES
      do
        echo $DIFF $file ~/.$file
        $DIFF $file ~/.$file
        echo ''
      done
    fi
    ;;

  install)
    if [ $2 ]
    then
      echo $CP $2 ~/.$2
      $CP $2 ~/.$2
    else
      for file in $FILES
      do
        echo $CP $file ~/.$file
        $CP $file ~/.$file
      done
    fi
    ;;

  vim-install)
    vim_install
    ;;

  clean)
    if [ $2 ]
    then
      echo $RM ~/.$2
      $RM ~/.$2
    else
      for file in $FILES
      do
        echo $RM ~/.$file
        $RM ~/.$file
      done
    fi
    ;;

  *)
    show_help
    ;;
esac
