#!/usr/bin/bash

echo ' s) Shutdown'
echo ' r) Reboot'
echo ' l) Logout'
echo ' b) Lock'
echo ' c) Cancel'

read -n 1 op

case $op in
	's')
		systemctl poweroff
		;;
	'r')
		systemctl reboot
		;;
	'l')
		wm_proc=$(ps -e | grep -e i3$ -e icewm-session | awk '{print $1}')
		kill -9 $wm_proc
		;;
    'b')
        i3lock -ni $WALLPAPER
        ;;
	'c')
		echo 'Bye'
		;;
	*)
		echo 'Not an option'
		;;
esac
