#!/bin/bash

DIR=$(pwd)
FILES='
conkyrc
gitconfig
i3
oh-my-zsh/custom
vim
vimrc
xinitrc
Xmodmap
Xresources
zshrc
'

for file in $FILES
do
  rm -v -rf ~/.$file ~/dotfiles_old
  ln -v -s $DIR/$file ~/.$file
done
