colorscheme monokai

set guioptions-=m
set guioptions-=T
set guioptions-=b
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set columns=100
set lines=50
set showtabline=1
set guicursor+=a:blinkon0
if has('win32')
    set guifont=Consolas:h10
else
    set guifont=Anonymous\ Pro\ 11
endif
