#!/bin/sh

# set wallpaper
feh --bg-scale ~/Pictures/Wallpapers/ISS.jpg

# set keymap mod
xmodmap ~/.Xmodmap

# set resources
xrdb ~/.Xresources

# open apps
firefox &
urxvt &
urxvt -title RSS -g 65x25 -e newsbeuter &
