#!/bin/sh

# set wallpaper
feh --bg-scale ~/Pictures/Wallpapers/ISS.jpg

# set keymap mod
xmodmap ~/.Xmodmap

# set resources
xrdb ~/.Xresources

# open apps
firefox &
pidgin &
turpial &
urxvt &
urxvt -title RSS -g 65x15 -e newsbeuter -r &
